# Generated by Django 4.0.2 on 2022-03-02 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Компания')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('logo_url', models.TextField(blank=True, verbose_name='URL логотипа')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображается?')),
            ],
            options={
                'verbose_name': 'IT-компании Гомеля',
                'verbose_name_plural': 'IT-компании Гомеля',
                'ordering': [django.db.models.functions.text.Lower('name'), 'id'],
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=255, verbose_name='Ресурс')),
                ('resource_url', models.CharField(max_length=255, verbose_name='Ссылка')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'ordering': ['resource'],
            },
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_text', models.CharField(max_length=255, verbose_name='Адрес')),
                ('adress_coords', models.CharField(blank=True, max_length=255, verbose_name='Координаты адреса')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['adress_text'],
            },
        ),
    ]
