# Generated by Django 4.0.2 on 2022-03-23 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_resources_resource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['address_text'], 'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adress_coords',
            new_name='address_coords',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adress_text',
            new_name='address_text',
        ),
    ]
